name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-scan:
    name: Build, Scan and Push Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      CACHE_IMAGE: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/zadanie2-cache:cache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase image name
        id: vars
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to DockerHub (for cache)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image with cache
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ env.CACHE_IMAGE }}
          cache-to: type=registry,ref=${{ env.CACHE_IMAGE }},mode=max

      - name: Scan pushed image with Trivy
        uses: aquasecurity/trivy-action@0.11.2
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH
