name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and export Docker image (with cache)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository_owner }}/weather-app:latest
        cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/weather-app-cache:latest
        cache-to: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/weather-app-cache:latest,mode=max
        outputs: type=docker,dest=image.tar

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: image.tar
        format: 'table'
        severity: 'HIGH,CRITICAL'
        exit-code: '1'

    - name: Load and push image to GHCR
      if: success()
      run: |
        docker load -i image.tar
        docker push ghcr.io/${{ github.repository_owner }}/weather-app:latest
